### PR TITLE
 Add ERV devices (Lossnay Energy Recovery Ventilators)

### PR DESCRIPTION
**Pull request by zaklex**
Available properties:

Read:

- name
- room_temperature
- outdoor_temperature
- fan_speeds
- fan_speed
- actual_supply_fan_speed
- actual_exhaust_fan_speed
- ventilation_modes
- ventilation_mode
- actual_ventilation_mode
- total_energy_consumed
- wifi_signal
- presets
- error_code
- core_maintenance_required
- filter_maintenance_required
- night_purge_mode
- room_co2_level 

Write:

- ventilation_mode
- fan_speed

### CODE REVIEW

**Comment by vilppuvuorinen** [comment]
Thanks for the PR. I'll try to take a closer look at it during this week.

**Comment by vilppuvuorinen** [comment]
@zaklex Are you planning to extend the home-assistant integration using this library?

**Comment by zaklex** [comment]
Yes

**Comment by vilppuvuorinen** [comment]
Nice. I'll make the `wifi_signal` and `error_code` available for all of the devices types and there's a login bug I want to fix in the same release. The new release should be out today.

I guess you are already planning to go with a `climate` device and mapping the ventilation mode to the hvac mode. If you have also planned adding a sensor for the wifi signal strenght, please add it for all device types.

**Comment by vilppuvuorinen** [comment]
@zaklex 2.9.0 is now released.

I did a couple of minor changes to the ERV device to match previous conventions:

- Renamed `outdoor_temperature` -> `outside_temperature` to match ATW device.
- Change mode and fan speed to return `None` if the update has not been called yet.

I didn't have enough time to address the login bug today. I ended up releasing without the fix because I didn't want to keep you waiting.

Thank you for contributing.

**Pull request merged**
